# -*- coding: utf-8 -*-
"""citizen AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176YxVLMS1M0epe_zYNu6cmiqzGbk1US3
"""

#install project libraries
!pip install transformers torch gradio PyPDF2

#install project libraries
!pip install transformers torch gradio PyPDF2

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import PyPDF2
import io

# Load model and tokenizer
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def generate_response(prompt, max_length=1024):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)

    if torch.cuda.is_available():
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=max_length,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    # slice off input tokens to avoid duplication
    gen_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    response = tokenizer.decode(gen_tokens, skip_special_tokens=True).strip()
    return response

def extract_text_from_pdf(pdf_file):
    if pdf_file is None:
        return ""

    try:
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        text = ""
        for page in pdf_reader.pages:
            text += page.extract_text() + "\n"
        return text
    except Exception as e:
        return f"Error reading PDF: {str(e)}"

# --- Citizen Complaint Draft Generator ---
def citizen_complaint_generator(issue_description):
    prompt = f"Draft a clear and polite citizen complaint for the issue: {issue_description}. " \
             f"Include location, impact on residents, and request timely action."
    return generate_response(prompt, max_length=1000)

# --- Policy Summarization ---
def policy_summarization(pdf_file, policy_text):
    # Get text from PDF or direct input
    if pdf_file is not None:
        content = extract_text_from_pdf(pdf_file)
        summary_prompt = f"Summarize the following government policy and extract the most important points, " \
                         f"benefits to citizens, and steps for application:\n\n{content}"
    else:
        content = policy_text  # Use policy_text when no file is uploaded
        summary_prompt = f"Summarize the following government policy and extract the most important points, " \
                         f"benefits to citizens, and steps for application:\n\n{content}"

    return generate_response(summary_prompt, max_length=1200)

# Create Gradio interface
with gr.Blocks() as app:
    gr.Markdown("# CitizenAI – Intelligent Citizen Engagement Platform")

    with gr.Tabs():
        # Complaint Generator
        with gr.TabItem("Citizen Complaint Generator"):
            with gr.Row():
                with gr.Column():
                    issue_input = gr.Textbox(
                        label="Describe Your Civic Issue",
                        placeholder="e.g., open pothole near bus stop, garbage not cleared, water leakage...",
                        lines=3
                    )
                    generate_complaint_btn = gr.Button("Generate Complaint Draft")

                with gr.Column():
                    complaint_output = gr.Textbox(
                        label="AI Generated Complaint Draft",
                        lines=15,
                        show_copy_button=True
                    )

            generate_complaint_btn.click(citizen_complaint_generator, inputs=issue_input, outputs=complaint_output)

        # Policy Summarization
        with gr.TabItem("Policy Summarization"):
            with gr.Row():
                with gr.Column():
                    pdf_upload = gr.File(label="Upload Policy PDF", file_types=[".pdf"])
                    policy_text_input = gr.Textbox(
                        label="Or paste policy text here",
                        placeholder="Paste policy document text...",
                        lines=5
                    )
                    summarize_btn = gr.Button("Summarize Policy")

                with gr.Column():
                    summary_output = gr.Textbox(
                        label="Policy Summary & Key Points",
                        lines=20,
                        show_copy_button=True
                    )

            summarize_btn.click(policy_summarization, inputs=[pdf_upload, policy_text_input], outputs=summary_output)

app.launch(share=True)

